export const ROUNDS_2026 = [
  { round: 1,  name: "Australian Grand Prix",     circuit: "Albert Park Circuit",            location: "Melbourne, Australia",     type: "permanent", flag: "🇦🇺", countryCode: "au" },
  { round: 2,  name: "Chinese Grand Prix",        circuit: "Shanghai International Circuit", location: "Shanghai, China",          type: "permanent", flag: "🇨🇳", countryCode: "cn" },
  { round: 3,  name: "Japanese Grand Prix",       circuit: "Suzuka International Circuit",   location: "Suzuka, Japan",            type: "permanent", flag: "🇯🇵", countryCode: "jp" },
  { round: 4,  name: "Bahrain Grand Prix",        circuit: "Bahrain International Circuit",  location: "Sakhir, Bahrain",          type: "permanent", flag: "🇧🇭", countryCode: "bh" },
  { round: 5,  name: "Saudi Arabian Grand Prix",  circuit: "Jeddah Corniche Circuit",        location: "Jeddah, Saudi Arabia",     type: "street",    flag: "🇸🇦", countryCode: "sa" },
  { round: 6,  name: "Miami Grand Prix",          circuit: "Miami International Autodrome",  location: "Miami, USA",               type: "permanent", flag: "🇺🇸", countryCode: "us" },
  { round: 7,  name: "Emilia Romagna Grand Prix", circuit: "Autodromo Enzo e Dino Ferrari",  location: "Imola, Italy",             type: "permanent", flag: "🇮🇹", countryCode: "it" },
  { round: 8,  name: "Monaco Grand Prix",         circuit: "Circuit de Monaco",              location: "Monte Carlo, Monaco",      type: "street",    flag: "🇲🇨", countryCode: "mc" },
  { round: 9,  name: "Spanish Grand Prix",        circuit: "Circuit de Barcelona-Catalunya", location: "Barcelona, Spain",         type: "permanent", flag: "🇪🇸", countryCode: "es" },
  { round: 10, name: "Canadian Grand Prix",       circuit: "Circuit Gilles Villeneuve",      location: "Montreal, Canada",         type: "permanent", flag: "🇨🇦", countryCode: "ca" },
  { round: 11, name: "Austrian Grand Prix",       circuit: "Red Bull Ring",                  location: "Spielberg, Austria",       type: "permanent", flag: "🇦🇹", countryCode: "at" },
  { round: 12, name: "British Grand Prix",        circuit: "Silverstone Circuit",            location: "Silverstone, UK",          type: "permanent", flag: "🇬🇧", countryCode: "gb" },
  { round: 13, name: "Belgian Grand Prix",        circuit: "Circuit de Spa-Francorchamps",   location: "Stavelot, Belgium",        type: "permanent", flag: "🇧🇪", countryCode: "be" },
  { round: 14, name: "Hungarian Grand Prix",      circuit: "Hungaroring",                    location: "Budapest, Hungary",        type: "permanent", flag: "🇭🇺", countryCode: "hu" },
  { round: 15, name: "Dutch Grand Prix",          circuit: "Circuit Zandvoort",              location: "Zandvoort, Netherlands",   type: "permanent", flag: "🇳🇱", countryCode: "nl" },
  { round: 16, name: "Italian Grand Prix",        circuit: "Autodromo Nazionale Monza",      location: "Monza, Italy",             type: "permanent", flag: "🇮🇹", countryCode: "it" },
  { round: 17, name: "Azerbaijan Grand Prix",     circuit: "Baku City Circuit",              location: "Baku, Azerbaijan",         type: "street",    flag: "🇦🇿", countryCode: "az" },
  { round: 18, name: "Singapore Grand Prix",      circuit: "Marina Bay Street Circuit",      location: "Singapore",                type: "street",    flag: "🇸🇬", countryCode: "sg" },
  { round: 19, name: "United States Grand Prix",  circuit: "Circuit of the Americas",        location: "Austin, USA",              type: "permanent", flag: "🇺🇸", countryCode: "us" },
  { round: 20, name: "Mexico City Grand Prix",    circuit: "Autodromo Hermanos Rodriguez",   location: "Mexico City, Mexico",      type: "permanent", flag: "🇲🇽", countryCode: "mx" },
  { round: 21, name: "São Paulo Grand Prix",      circuit: "Autodromo Jose Carlos Pace",     location: "São Paulo, Brazil",        type: "permanent", flag: "🇧🇷", countryCode: "br" },
  { round: 22, name: "Abu Dhabi Grand Prix",      circuit: "Yas Marina Circuit",             location: "Abu Dhabi, UAE",           type: "permanent", flag: "🇦🇪", countryCode: "ae" },
];