export const ROUNDS_2026 = [
  { round: 1,  name: "Australian Grand Prix",   location: "Melbourne",         flag: "🇦🇺", circuit: "Albert Park Circuit",                  type: "permanent" },
  { round: 2,  name: "Chinese Grand Prix",       location: "Shanghai",          flag: "🇨🇳", circuit: "Shanghai International Circuit",       type: "permanent" },
  { round: 3,  name: "Japanese Grand Prix",      location: "Suzuka",            flag: "🇯🇵", circuit: "Suzuka Circuit",                        type: "permanent" },
  { round: 4,  name: "Miami Grand Prix",         location: "Miami Gardens",     flag: "🇺🇸", circuit: "Miami International Autodrome",        type: "street"    },
  { round: 5,  name: "Canadian Grand Prix",      location: "Montréal",          flag: "🇨🇦", circuit: "Circuit Gilles Villeneuve",             type: "permanent" },
  { round: 6,  name: "Monaco Grand Prix",        location: "Monte Carlo",       flag: "🇲🇨", circuit: "Circuit de Monaco",                    type: "street"    },
  { round: 7,  name: "Barcelona Grand Prix",     location: "Barcelona",         flag: "🇪🇸", circuit: "Circuit de Barcelona-Catalunya",       type: "permanent" },
  { round: 8,  name: "Austrian Grand Prix",      location: "Spielberg",         flag: "🇦🇹", circuit: "Red Bull Ring",                        type: "permanent" },
  { round: 9,  name: "British Grand Prix",       location: "Silverstone",       flag: "🇬🇧", circuit: "Silverstone Circuit",                  type: "permanent" },
  { round: 10, name: "Belgian Grand Prix",       location: "Spa-Francorchamps", flag: "🇧🇪", circuit: "Circuit de Spa-Francorchamps",         type: "permanent" },
  { round: 11, name: "Hungarian Grand Prix",     location: "Budapest",          flag: "🇭🇺", circuit: "Hungaroring",                          type: "permanent" },
  { round: 12, name: "Dutch Grand Prix",         location: "Zandvoort",         flag: "🇳🇱", circuit: "Circuit Zandvoort",                    type: "permanent" },
  { round: 13, name: "Italian Grand Prix",       location: "Monza",             flag: "🇮🇹", circuit: "Autodromo Nazionale Monza",            type: "permanent" },
  { round: 14, name: "Spanish Grand Prix",       location: "Madrid",            flag: "🇪🇸", circuit: "Circuit de Madrid",                    type: "street"    },
  { round: 15, name: "Azerbaijan Grand Prix",    location: "Baku",              flag: "🇦🇿", circuit: "Baku City Circuit",                    type: "street"    },
  { round: 16, name: "Singapore Grand Prix",     location: "Marina Bay",        flag: "🇸🇬", circuit: "Marina Bay Street Circuit",            type: "street"    },
  { round: 17, name: "United States Grand Prix", location: "Austin",            flag: "🇺🇸", circuit: "Circuit of the Americas",              type: "permanent" },
  { round: 18, name: "Mexico City Grand Prix",   location: "Mexico City",       flag: "🇲🇽", circuit: "Autodromo Hermanos Rodriguez",         type: "permanent" },
  { round: 19, name: "São Paulo Grand Prix",     location: "São Paulo",         flag: "🇧🇷", circuit: "Autodromo Jose Carlos Pace",           type: "permanent" },
  { round: 20, name: "Las Vegas Grand Prix",     location: "Las Vegas",         flag: "🇺🇸", circuit: "Las Vegas Strip Circuit",              type: "street"    },
  { round: 21, name: "Qatar Grand Prix",         location: "Lusail",            flag: "🇶🇦", circuit: "Lusail International Circuit",         type: "permanent" },
  { round: 22, name: "Abu Dhabi Grand Prix",     location: "Yas Marina",        flag: "🇦🇪", circuit: "Yas Marina Circuit",                   type: "permanent" },
];
